### PR TITLE
Performance improvement and element resize watcher

### PR DESCRIPTION
**Pull request by HuangJian**

### CODE REVIEW

**Comment by miraclemarc** [comment]
Tested +1 for performance improvement

**Comment by HuangJian** [comment]
@miraclemarc 

Please update to my latest change this morning.
My previous change places the ellipsis not so accurate...

**Comment by dibari** [comment]
I'll take a look at the pull request this evening and merge it then - thanks for the update!

**Comment by a-c-m** [comment]
This works much better than the current version. For our implementation the current version failed to work at all. This one works fine.

**Comment by MauMaGau** [comment]
I'm getting an error with the PR:
image

**Pull request closed without merging**
