### PR TITLE
Additional check for checking if SCE (Strict Contextual Escaping) is enabled

### PR DESCRIPTION
**Pull request by amri**

### CODE REVIEW

**Comment by amri** [comment]
Could you review this?

**Comment by MauMaGau** [comment]
Thanks @amri Could you fix the merge conflicts and I'll merge and tag it.

**Comment by amri** [comment]
I have merged the conflict.

**Comment by amri** [comment]
Could you merge and tag it?

**Comment by amri** [comment]
@MauMaGau , when can we merge this item ?

**Comment by MauMaGau** [comment]
Tagged as 0.1.6

**Pull request merged**
